version: '3'
volumes:
  db:
services:
  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
  api:
    build: .
    volumes:
      - ./src:/code/src
      - ./package.json:/code/package.json
    env_file: .env
    ports: 
      - 6868:6868
      - 587:587
    restart: unless-stopped
